root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ."
  bin = "./tmp/main"
  full_bin = "APP_ENV=development ./tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor", "frontend", "migrations", "db"]
  log = "air_build.log"
  delay = 1000 # ms

[run]
  cmds = ["./tmp/main"]
  log = "air_run.log"

[misc]
  clean_on_exit = true
